language: python
python: 2.7
branches:
  only:
    - master
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|dev\d+)?$/

services:
  - docker
  - mysql
  - postgresql
  - redis-server

env:
  matrix:
    - TOXENV=py27
    - TOXENV=flake8

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
      services:
        - docker
        - mysql
        - postgresql
        - redis-server
    - python: 3.6
      env: TOXENV=py36
      services:
        - docker
        - mysql
        - postgresql
        - redis-server
    - python: 3.7
      env: TOXENV=py37
      services:
        - docker
        - mysql
        - postgresql
        - redis-server

install:
  - pip install -U tox wheel codecov
  - pip install -r requirements/tests.txt

before_install:
  - make run

before_script:
  - mysql -u root -e "set global innodb_large_prefix=1;"
  - mysql -u root -e "set global innodb_file_format='Barracuda';"
  - mysql -u root -e "set global innodb_file_per_table=true;"
  - tests/run_zmq_broker.sh
  - docker-compose up -d

script: tox

after_success:
  - codecov

after_script:
  - cat broker.log

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: bG1ycgBJrVfgBsHAwaWScL2V1x52/aZy2znE2kFzFfYq95HS51mu1GO2PKwpATJyMCs/xUIKGhiBtoo8LzNmNU2kPgarQFwzpLkx2ninOm+3uAwuIfGGWsonBW/h854n+cNwppJOlfEOxvMVerVVpdV4EFeJfEkVYascwOBbnqo=
  on:
    branch: master
    tags: true
    condition: $TOXENV == py27
